CC = gcc

CFLAGS = -Iinclude -g -ansi -std=c89 -pedantic -Wall -Wextra -O3

SRC = $(shell dir /s /b src\*.c)
OBJ = $(SRC:.c=.o)

TARGET = build\main.exe

$(TARGET): $(OBJ)
	$(CC) -o $@ $(OBJ)

src/%.o: src/%.c
	$(CC) $(CFLAGS) -c -o $@ $<

echo:
	@echo "Source files: $(SRC)"

clear:
	del /s /q *.o
	del /q $(TARGET)

run: $(TARGET)
	$(TARGET)
